# Iris Flower Classifier

In [69]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [70]:
# Importing dataset

dataset = pd.read_csv('IRIS.xls')
dataset

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [71]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [72]:
dataset.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [73]:
dataset.shape

(150, 5)

In [74]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [75]:
dataset.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [76]:
dataset['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

For the model to train properly it is needed to shuffle this dataset 

In [77]:
# Shuffling dataset
dataset = dataset.sample(frac=1, random_state = 1)
# After shuffling resetting the index
dataset = dataset.reset_index(drop=True)

In [78]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width          species
0           5.8          4.0           1.2          0.2      Iris-setosa
1           5.1          2.5           3.0          1.1  Iris-versicolor
2           6.6          3.0           4.4          1.4  Iris-versicolor
3           5.4          3.9           1.3          0.4      Iris-setosa
4           7.9          3.8           6.4          2.0   Iris-virginica

In [79]:
specieses = dataset['species']
specieses = list(specieses)

encoded_species = []

for species in specieses:
    if species == 'Iris-setosa':
        encoded_species.append(0)
    elif species == 'Iris-versicolor':
        encoded_species.append(1)
    else:
        encoded_species.append(2)

In [81]:
encoded_species

[0,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 0,
 1,
 0,
 1,
 2,
 2,
 0,
 2,
 2,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 0,
 2,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 2,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 0]

In [82]:
dataset['encoded_species'] = encoded_species
dataset

sepal_length  sepal_width  petal_length  petal_width          species  \
0             5.8          4.0           1.2          0.2      Iris-setosa   
1             5.1          2.5           3.0          1.1  Iris-versicolor   
2             6.6          3.0           4.4          1.4  Iris-versicolor   
3             5.4          3.9           1.3          0.4      Iris-setosa   
4             7.9          3.8           6.4          2.0   Iris-virginica   
..            ...          ...           ...          ...              ...   
145           6.3          2.8           5.1          1.5   Iris-virginica   
146           6.4          3.1           5.5          1.8   Iris-virginica   
147           6.3          2.5           4.9          1.5  Iris-versicolor   
148           6.7          3.1           5.6          2.4   Iris-virginica   
149           4.9          3.1           1.5          0.1      Iris-setosa   

     encoded_species  
0                  0  
1                  1  
2                  1  
3                  0  
4                  2  
..               ...  
145                2  
146                2  
147                1  
148                2  
149                0  

[150 rows x 6 columns]

In [83]:
dataset.drop(columns='species', inplace=True)

In [84]:
dataset

sepal_length  sepal_width  petal_length  petal_width  encoded_species
0             5.8          4.0           1.2          0.2                0
1             5.1          2.5           3.0          1.1                1
2             6.6          3.0           4.4          1.4                1
3             5.4          3.9           1.3          0.4                0
4             7.9          3.8           6.4          2.0                2
..            ...          ...           ...          ...              ...
145           6.3          2.8           5.1          1.5                2
146           6.4          3.1           5.5          1.8                2
147           6.3          2.5           4.9          1.5                1
148           6.7          3.1           5.6          2.4                2
149           4.9          3.1           1.5          0.1                0

[150 rows x 5 columns]

In [85]:
x = dataset.iloc[:, :4].values
y = dataset.iloc[:,-1].values

In [86]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

In [89]:
# from sklearn.preprocessing import StandardScaler
# standard_scalar = StandardScaler()
# x_train = standard_scalar.fit_transform(x_train)
# x_test = standard_scalar.transform(x_test)

In [99]:
# print(x_train)

[[-1.13571076  0.04976826 -1.25535237 -1.41425917]
 [-0.14634386 -0.40963109  0.28589116  0.15956865]
 [ 1.09036478  0.04976826  0.40005735  0.29072097]
 [-1.13571076 -0.17993141 -1.31243546 -1.28310685]
 [ 0.10099787  0.27946794  0.62838972  0.81533025]
 [-1.25938163 -0.17993141 -1.31243546 -1.15195453]
 [ 1.33770651  0.04976826  0.97088828  1.20878721]
 [ 0.3483396  -0.63933076  0.57130663  0.02841634]
 [ 1.83238996 -0.40963109  1.48463613  0.81533025]
 [-1.25938163  0.73886729 -1.02701999 -1.28310685]
 [-1.0120399   0.50916761 -1.31243546 -1.28310685]
 [-0.27001472 -0.17993141  0.45714044  0.42187329]
 [-1.13571076 -1.32842979  0.45714044  0.68417793]
 [-0.39368558 -1.55812947  0.05755879 -0.10273598]
 [ 2.32707342 -0.63933076  1.7129685   1.07763489]
 [ 0.84302305 -0.17993141  0.8567221   1.07763489]
 [-0.51735645  0.73886729 -1.25535237 -1.02080222]
 [ 2.57441514  1.65766599  1.54171922  1.07763489]
 [ 2.32707342 -1.09873012  1.82713469  1.47109184]
 [-0.14634386 -0.17993141  0.28

In [90]:
from sklearn.linear_model import LogisticRegression

logistic_regressor = LogisticRegression()
logistic_regressor.fit(x_train, y_train)

LogisticRegression()

In [100]:
y_pred = logistic_regressor.predict(x_test)

In [102]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  2 10]]


0.9333333333333333

In [103]:
from sklearn.ensemble import RandomForestClassifier
random_forest_classifier = RandomForestClassifier()
random_forest_classifier.fit(x_train, y_train)

RandomForestClassifier()

In [104]:
y_pred = random_forest_classifier.predict(x_test)

In [105]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  2 10]]


0.9333333333333333

In [106]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [107]:
y_pred = decision_tree_classifier.predict(x_test)

In [108]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  2 10]]


0.9333333333333333