# Iris Flower Classifier

In [110]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [111]:
# Importing dataset

dataset = pd.read_csv('IRIS.xls')
dataset

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [112]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [113]:
dataset.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [114]:
dataset.shape

(150, 5)

In [115]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [116]:
dataset.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [117]:
dataset['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

For the model to train properly it is needed to shuffle this dataset 

In [118]:
# Shuffling dataset
dataset = dataset.sample(frac=1, random_state = 1)
# After shuffling resetting the index
dataset = dataset.reset_index(drop=True)

In [119]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width          species
0           5.8          4.0           1.2          0.2      Iris-setosa
1           5.1          2.5           3.0          1.1  Iris-versicolor
2           6.6          3.0           4.4          1.4  Iris-versicolor
3           5.4          3.9           1.3          0.4      Iris-setosa
4           7.9          3.8           6.4          2.0   Iris-virginica

In [120]:
specieses = dataset['species']
specieses = list(specieses)

encoded_species = []

for species in specieses:
    if species == 'Iris-setosa':
        encoded_species.append(0)
    elif species == 'Iris-versicolor':
        encoded_species.append(1)
    else:
        encoded_species.append(2)

In [121]:
encoded_species

[0,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 0,
 1,
 0,
 1,
 2,
 2,
 0,
 2,
 2,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 0,
 2,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 2,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 0]

In [122]:
dataset['encoded_species'] = encoded_species
dataset

sepal_length  sepal_width  petal_length  petal_width          species  \
0             5.8          4.0           1.2          0.2      Iris-setosa   
1             5.1          2.5           3.0          1.1  Iris-versicolor   
2             6.6          3.0           4.4          1.4  Iris-versicolor   
3             5.4          3.9           1.3          0.4      Iris-setosa   
4             7.9          3.8           6.4          2.0   Iris-virginica   
..            ...          ...           ...          ...              ...   
145           6.3          2.8           5.1          1.5   Iris-virginica   
146           6.4          3.1           5.5          1.8   Iris-virginica   
147           6.3          2.5           4.9          1.5  Iris-versicolor   
148           6.7          3.1           5.6          2.4   Iris-virginica   
149           4.9          3.1           1.5          0.1      Iris-setosa   

     encoded_species  
0                  0  
1                  1  
2                  1  
3                  0  
4                  2  
..               ...  
145                2  
146                2  
147                1  
148                2  
149                0  

[150 rows x 6 columns]

In [123]:
dataset.drop(columns='species', inplace=True)

In [124]:
dataset

sepal_length  sepal_width  petal_length  petal_width  encoded_species
0             5.8          4.0           1.2          0.2                0
1             5.1          2.5           3.0          1.1                1
2             6.6          3.0           4.4          1.4                1
3             5.4          3.9           1.3          0.4                0
4             7.9          3.8           6.4          2.0                2
..            ...          ...           ...          ...              ...
145           6.3          2.8           5.1          1.5                2
146           6.4          3.1           5.5          1.8                2
147           6.3          2.5           4.9          1.5                1
148           6.7          3.1           5.6          2.4                2
149           4.9          3.1           1.5          0.1                0

[150 rows x 5 columns]

In [125]:
x = dataset.iloc[:, :4].values
y = dataset.iloc[:,-1].values

In [126]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=1)

In [127]:
# from sklearn.preprocessing import StandardScaler
# standard_scalar = StandardScaler()
# x_train = standard_scalar.fit_transform(x_train)
# x_test = standard_scalar.transform(x_test)

In [128]:
# print(x_train)

In [129]:
from sklearn.linear_model import LogisticRegression

logistic_regressor = LogisticRegression()
logistic_regressor.fit(x_train, y_train)

C:\Users\masan\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [130]:
y_pred = logistic_regressor.predict(x_test)

In [131]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  1 11]]


0.9666666666666667

In [132]:
from sklearn.ensemble import RandomForestClassifier
random_forest_classifier = RandomForestClassifier()
random_forest_classifier.fit(x_train, y_train)

RandomForestClassifier()

In [133]:
y_pred = random_forest_classifier.predict(x_test)

In [134]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  2 10]]


0.9333333333333333

In [135]:
from sklearn.tree import DecisionTreeClassifier
decision_tree_classifier = DecisionTreeClassifier()
decision_tree_classifier.fit(x_train, y_train)

DecisionTreeClassifier()

In [136]:
y_pred = decision_tree_classifier.predict(x_test)

In [137]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  2 10]]


0.9333333333333333